name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main   # change to your real default branch if needed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello from GitHub Actions"
